version: '3'

services:
  postgres:
    image: postgis/postgis:12-2.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always

  explorer:
    build: 
        context: .
        dockerfile: Dockerfile_explorer
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
    links:
      - postgres:postgres
    ports:
      - 9001:9000
    restart: always
    
  openeo_odc_driver:
    build: 
        context: .
        dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_NO_SIGN_REQUEST=true
    links:
      - postgres:postgres
      - explorer:explorer
    ports:
      - 5001:5000
    volumes:
      - ~/tmp/:/tmp/
    restart: always
    
  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    links:
      - postgres:postgres
