name: openeo_odc
channels:
- conda-forge
dependencies:
- python=3.8
- datacube
- numpy
- geopandas
- geocube
- xarray
- rasterio
- rioxarray
- dask
- dask-ml
- distributed
- dask-geopandas
- xgboost
- scikit-learn
- scipy
- pip
- requests
- libnetcdf
- netCDF4
- h5netcdf
- libgdal
- gdal
- geos
- proj
- gunicorn
- flask
- opencv
- rpy2
- r-base
- r-stars
- r-lubridate
- r-jsonlite
- r-curl
- r-caret
- r-randomforest
- pip
- pip:
    - --extra-index-url https://packages.dea.ga.gov.au
    - openeo
    - openeo_r_udf
    - dea-tools
    - odc-algo
    - git+https://github.com/Open-EO/openeo-pg-parser-python.git
     