name: openeo_odc_driver
channels:
- conda-forge
dependencies:
- python=3.11
- pydantic=2.8.2
- libgcc=5.2.0
- datacube
- numpy<2
- pandas
- geopandas
- geocube
- xarray
- rasterio
- rioxarray
- dask
- distributed
- scikit-learn
- scipy
- libnetcdf
- netCDF4
- h5netcdf
- libgdal
- gdal
- geos
- proj
- gunicorn
- flask
- opencv
- pip
- pip:
    - openeo[localprocessing]
    - dea-tools
    - raster2stac
    - ujson
    - rio-stac